# Generated by Django 4.2.30 on 2026-06-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_recurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('none', 'No recurrence'), ('daily', 'Every day'), ('weekly', 'Every week'), ('weekly', 'Every weekday'), ('monthly', 'Every month')], default='none', max_length=10),
        ),
    ]
