# Generated by Django 4.2.30 on 2026-06-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_category_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence_weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Used when recurrence is "Every specific day of week"', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('none', 'No recurrence'), ('daily', 'Every day'), ('weekday', 'Every weekday (Mon–Fri)'), ('weekly', 'Every week'), ('weekday_on', 'Every specific day of week'), ('monthly', 'Every month')], default='none', max_length=12),
        ),
    ]
